Настроить автоматизацию процесса разработки; FIX #1
alex-koshara/pink pull request #6
Opened 2017-01-10 19:45 UTC by alex-koshara

#1

2017-01-10 20:12 UTC, isqua requested changes

2017-01-10 20:12 UTC, isqua commented on package.json
> +  },
Сделай чтобы можно было сказать `npm start` и кодить?

2017-01-10 20:12 UTC, isqua commented on .gitignore
> +node_modules/
<img width="25" alt="EOL" src="https://cloud.githubusercontent.com/assets/529247/21822589/d8249728-d788-11e6-8ae6-8bbe1cfd45a2.png">
Так гитхаб тебе намекает, что принято оставлять пустые строки в конце файлов, а у тебя нету.

2017-01-10 20:12 UTC, isqua commented on form.html
> +  <script>svg4everybody();</script>
Если мне не изменяет память, какую-то из этих библиотек можно подключать в конце документа, но одну точно нужно в шапке. Какую куда и почему?

2017-01-10 20:12 UTC, isqua commented on gulpfile.js
> +  .pipe(svgmin())
Пожалуйсто довайте не занимать время сборки оптимизацией картинок.

2017-01-10 20:12 UTC, isqua commented on gulpfile.js
> +    .pipe(gulp.dest("./css"));
У тебя два раза дестинейшн css. Это странно!

2017-01-10 20:12 UTC, isqua commented on gulpfile.js
> +      paths: [ path.join(__dirname, 'less', 'includes') ]
Про что эта строка?

2017-01-10 20:12 UTC, isqua commented on gulpfile.js
> +});
Вот тут тоже не хватает перевода в конце строки.

2017-01-10 20:12 UTC, isqua commented on img/icons.svg
> +<svg xmlns="http://www.w3.org/2000/svg"><symbol id="icon-facebook" viewBox="0 0 8.673 18.944"><path fill="currentColor" d="M6.275 3.357h2.398V0H5.795C2.656.181 1.54 2.387 1.948 6.115H0v3.517h1.958v9.
Результат сборки не должен попадать в репозиторий.

2017-01-10 20:12 UTC, isqua commented on img/icons/icon-facebook.svg
> +<svg version="1" xmlns="http://www.w3.org/2000/svg" width="8.673" height="18.944" viewBox="0 0 8.673 18.944"><path fill="currentColor" d="M6.275 3.357h2.398V0H5.795C2.656.181 1.54 2.387 1.948 6.115H0
Давай хотя бы ширину и высоту округлять.  9 и 19 получится тут.

2017-01-10 20:13 UTC, isqua commented on .gitignore
> +node_modules/
Можешь эдиторконфиг добавить для этой цели.

2017-01-10 20:22 UTC, isqua commented on gulpfile.js
> +gulp.task('less', function () {
Кавычки то двойные, то одинарные. Надо определиться.

2017-01-10 20:22 UTC, isqua commented on gulpfile.js
> +  .pipe(svgmin())
Тут кстати табуляция поехала. В less-таске красивые отступы, а тут что-то нет.

2017-01-10 20:22 UTC, isqua commented on gulpfile.js
> +  .pipe(gulp.dest("img/"));
Было бы круто и иконки пересобирать, когда они изменяются или добавляются новые.

2017-01-10 20:22 UTC, isqua commented on package.json
> +    "gulp": "^3.9.1"
А почему этот парень в депенденсях, а остальные в девдепенденсях?

2017-01-10 20:22 UTC, isqua commented on img/icons/icon-twitter.svg
> +<svg version="1" xmlns="http://www.w3.org/2000/svg" width="17.5" height="14.663" viewBox="0 0 17.5 14.663"><path fill="currentColor" d="M11.283.153c1.736-.485 3.074.263 3.685 1.151.694-.226 1.372-.47
Раз они все у тебя в папке icons, можно не добавлять префикс icon им в имя?

2017-01-10 20:22 UTC, isqua commented
Лан, давай пока скрипты не собирать.

2017-01-10 21:25 UTC, isqua commented
Ты ведь ещё не закончил?

2017-01-11 17:48 UTC, alex-koshara commented
ещё нет

2017-01-11 17:55 UTC, alex-koshara commented on form.html
> +  <script>svg4everybody();</script>
какую именно - не знаю. Если есть событие, что ждет пока DOM загрузится, то можно и в начале добавить, если нет, то в конце. Поэтому все в самом начале добавлю, не знаю где что есть. Шляпа в том, что DOM не прогрузится, пока они не выполнятся, но здесь не критично же, ошибок нет.

2017-01-11 17:55 UTC, alex-koshara commented on gulpfile.js
> +      paths: [ path.join(__dirname, 'less', 'includes') ]
про копирование куска кода из документации :)

2017-01-11 18:18 UTC, alex-koshara commented on js/picturefill.min.js
> +!function(a,b){"function"==typeof define&&define.amd?define([],function(){return a.svg4everybody=b()}):"object"==typeof exports?module.exports=b():a.svg4everybody=b()}(this,function(){function a(a,b)
отписал слак

2017-01-11 20:42 UTC, isqua commented on form.html
> +  <script>svg4everybody();</script>
> Шляпа в том, что DOM не прогрузится, пока они не выполнятся, но здесь не критично же, ошибок нет.

Проблема-то не в ошибках, а в том, что пользователь дольше ждёт загрузки страницы и смотрит на белый экран.

2017-01-11 20:42 UTC, isqua commented on gulpfile.js
> +  gulp.watch('img/icons/*.svg', ['symbols']).on('change', server.reload);
А почему лесс-таска релоадится, хотя у неё нету вот этого `on('change'`?

2017-01-11 20:42 UTC, isqua commented on gulpfile.js
> +  gulp.watch('*.html').on('change', server.reload);
Тут-то понятно: про хтмл нет отдельной таски. А про симболз есть.

2017-01-11 20:42 UTC, isqua commented on .gitignore
> +js/!main.js
Есть такой трюк: все «чужие» файлы складывать в папку vendor и игнорить её. Типа `js/vendor/`. Тогда тебе не придётся разыгноривать main.js. Вдруг у тебя кроме него ещё файлы будут, их тоже дописывать сюда?

2017-01-11 20:50 UTC, alex-koshara commented on gulpfile.js
> +  gulp.watch('img/icons/*.svg', ['symbols']).on('change', server.reload);
здесь настал момент "заработало! Вдохнуть и не дышать!"

2017-01-11 20:52 UTC, isqua commented on gulpfile.js
> +  gulp.watch('img/icons/*.svg', ['symbols']).on('change', server.reload);
Лол :) Разберись, как это работает.

2017-01-11 20:52 UTC, alex-koshara commented on gulpfile.js
> +  gulp.watch('img/icons/*.svg', ['symbols']).on('change', server.reload);
Если убрать, у меня, получается что svg не обновляется на странице (если саму svg иконку менять), пока не сохраню что-нибудь из html файлов

2017-01-11 21:07 UTC, isqua commented on gulpfile.js
> +  gulp.watch('img/icons/*.svg', ['symbols']).on('change', server.reload);
Так ты можешь объяснить, почему так? И почему со стилями всё нормально?

2017-01-12 03:49 UTC, alex-koshara commented on gulpfile.js
> +  gulp.watch('img/icons/*.svg', ['symbols']).on('change', server.reload);
пока не могу

2017-01-12 21:02 UTC, isqua commented on img/icons.svg
> +<svg xmlns="http://www.w3.org/2000/svg"><symbol id="facebook" viewBox="0 0 8.673 18.944"><path fill="currentColor" d="M6.275 3.357h2.398V0H5.795C2.656.181 1.54 2.387 1.948 6.115H0v3.517h1.958v9.312h3
Это результат сборки? Тогда его надо удалить отсюда и игнорить.

2017-01-12 21:02 UTC, isqua commented on index.html
> +  <script src="js/svg4everybody.min.js"></script>
Скрипты не грузятся.

2017-01-12 21:02 UTC, isqua commented on .gitignore
> +js/!main.js
?

2017-01-12 21:02 UTC, isqua commented on .gitignore
> +node_modules/
Тут ещё не хватает `*.log*` чтобы всякие npm-debug.log не сохранялись.

2017-01-12 21:40 UTC, isqua commented on gulpfile.js
> +    .pipe(gulp.dest('./css'))
Сорсмапы у тебя не работают. Я ставлю на боди жёлтый фон и вот что вижу в инспекторе:
<img width="280" alt="pink" src="https://cloud.githubusercontent.com/assets/529247/21909396/cd213402-d928-11e6-8827-70361538be1b.png">
А вот что хочу видеть:
<img width="280" alt="pink" src="https://cloud.githubusercontent.com/assets/529247/21909417/ea105610-d928-11e6-9bcb-e99ddf4ea82b.png">
Видишь разницу?

2017-01-12 21:43 UTC, isqua commented
Осталось:

[ ] удалить css/style.css — он просочился;
[ ] разобраться с сорсмапами;
[ ] изолировать библиотеки скриптов, чтобы игнорить только библиотеки.

Всё остальное хорошо!

2017-01-13 18:40 UTC, isqua commented
При первом запуске `npm start` на чистой копии репозитория icons.svg не собирается.

2017-01-13 18:42 UTC, isqua approved these changes
🎱 🔥

2017-01-13 20:33 UTC, merged