Сверстать хедер; FIX #4
alex-koshara/pink pull request #8
Opened 2017-01-14 21:30 UTC by alex-koshara

#4

2017-01-15 12:43 UTC, isqua commented
Руку давай в задаче про хедер на главной делать.

<img width="890" alt="default" src="https://cloud.githubusercontent.com/assets/529247/21962536/47e3604a-db39-11e6-84d3-5e731db28a35.png">

2017-01-15 14:50 UTC, alex-koshara commented
![image](https://cloud.githubusercontent.com/assets/16765673/21963405/0c3816aa-db4b-11e6-8840-b514320404e7.png)
Я думал это к заголовку относится или не?

2017-01-15 16:43 UTC, isqua commented
Шапка на главной разительно отличается от шапок на других страницах. Вот
то, что её отличает, делать не нужно, про это есть отдельная задача.

А шапки на остальных страницах конечно должны быть готовы.

On Sun, 15 Jan 2017 at 17:50, Alexander <notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/16765673/21963405/0c3816aa-db4b-11e6-8840-b514320404e7.png>
>
>
> Я думал это к заголовку относится или не?
>
>
>
>
> —
> You are receiving this because you were assigned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/alex-koshara/pink/pull/8#issuecomment-272699922>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAgTXy-Mi2eEoOVod-8bZF6LxYJe_nFaks5rSjIqgaJpZM4Ljv7K>
> .
>

2017-01-15 18:10 UTC, isqua requested changes

2017-01-15 18:10 UTC, isqua commented on less/components/header.less
> +    min-height: 730px;
Откуда это число?

2017-01-15 18:10 UTC, isqua commented on less/components/header.less
> +    min-height: 855px;
Откуда это число?

2017-01-15 18:10 UTC, isqua commented on less/components/header.less
> +  min-height: 462px;
Откуда это число?

2017-01-15 18:10 UTC, isqua commented on photo.html
> +    <div class="header__top">
Макет | Вёрстка
---- | ----
<img width="320" alt="макет" src="https://cloud.githubusercontent.com/assets/529247/21964945/8a1b9144-db66-11e6-88aa-10292167a3b0.png"> |  <img width="320" alt="default" src="https://cloud.githubusercontent.com/assets/529247/21964958/b1cc4db4-db66-11e6-9738-ae249b6f346a.png">
pink-photo-mobile.png | photo.html в Chrome в адаптивном режиме iPhone 5

Какие видишь отличия в шапке?

2017-01-15 18:23 UTC, alex-koshara commented on less/components/header.less
> +  min-height: 462px;
с макета

2017-01-15 18:23 UTC, alex-koshara commented on less/components/header.less
> +    min-height: 730px;
так же с макета

2017-01-15 18:23 UTC, alex-koshara commented on less/components/header.less
> +    min-height: 855px;
и это с макета

2017-01-15 18:24 UTC, alex-koshara commented on less/components/header.less
> +    min-height: 855px;
все с индекса правда брал

2017-01-15 18:25 UTC, alex-koshara commented on photo.html
> +    <div class="header__top">
разные высоты

2017-01-15 18:34 UTC, isqua commented on photo.html
> +    <div class="header__top">
И всё что ли?

2017-01-15 18:34 UTC, isqua commented on less/components/header.less
> +    min-height: 855px;
> все с индекса правда брал

Так про индекс отдельная задача, мы к нему ещё вернёмся в ней. Мне надо, чтобы на других страницах были нормальные шапки, чтобы больше к ним не возвращаться.

2017-01-15 18:37 UTC, alex-koshara commented on photo.html
> +    <div class="header__top">
разная центровка фона, отсутствие заголовка

2017-01-15 18:38 UTC, isqua commented on photo.html
> +    <div class="header__top">
Точно! И ещё кое-что: под лого и кнопкой фон чуть затемнён в макете, а у тебя такой же.

2017-01-15 19:21 UTC, isqua commented on less/components/main-nav.less
> +    text-transform: capitalize;
Почему именно такое?

2017-01-15 19:21 UTC, isqua commented on less/components/main-nav.less
> +  @media @desktop-widths {
У тебя две медиаквери про десктоп?

2017-01-15 19:21 UTC, isqua commented on less/components/main-nav.less
> +    &:nth-child(4n) {
Почему четвертый?

2017-01-15 19:21 UTC, isqua commented on less/components/main-nav.less
> +      width: 66,6%;
Это свойство работает?

2017-01-15 19:21 UTC, isqua commented on less/components/main-nav.less
> +      align-items: flex-start;
А это для чего?

2017-01-15 19:21 UTC, isqua commented on less/components/main-nav.less
> +  border-top: 1px solid @greyLight;
<img width="234" alt="default" src="https://cloud.githubusercontent.com/assets/529247/21965409/69723a4c-db70-11e6-8b1b-f1debbe09a14.png">
Рамка над «Главная» кажется чуть толще, чем над остальными.

2017-01-15 19:21 UTC, isqua commented on less/components/main-nav.less
> +    background: @blueDark;
Если открыть меню на планшете, а потом растянуть окно до десктопа, можно наблюдать удивительную картину:
<img width="1015" alt="default" src="https://cloud.githubusercontent.com/assets/529247/21965442/e2d1202e-db70-11e6-9fac-7959705904bf.png">
Не думаю, что у пользователей это будет частый случай, но поправить настолько дёшево, что я считаю, стоит поправить.

2017-01-15 19:50 UTC, alex-koshara commented on photo.html
> +    <div class="header__top">
ну он у меня тоже затемнен, просто там альфа-канал 0.3, вроде с макета стянул, но выглядит не так как в макете. Сделаю темнее

2017-01-15 19:53 UTC, alex-koshara commented on less/components/main-nav.less
> +    background: @blueDark;
интересно получилось)

2017-01-15 19:56 UTC, alex-koshara commented on less/components/main-nav.less
> +    text-transform: capitalize;
да, чет не то, если 2 слова вписать, то и второе будет с заглавной буквы, надо просто отменить.

2017-01-15 20:02 UTC, alex-koshara commented on less/components/main-nav.less
> +      width: 66,6%;
уже заработало. Через точку

2017-01-15 20:13 UTC, alex-koshara commented on less/components/main-nav.less
> +      align-items: flex-start;
видимо что-то пробовал и забыл удалить

2017-01-15 20:17 UTC, alex-koshara commented on less/components/main-nav.less
> +  @media @desktop-widths {
исправил

2017-01-15 20:39 UTC, alex-koshara commented on less/components/main-nav.less
> +    margin-right: auto;
чет не могу придумать, как хорошо сверстать, чтобы и по макету было и при переполнение было все хорошо

2017-01-16 18:08 UTC, isqua commented
Саша, сейчас это полуфабрикат. Ни индекс не готов, потому что там ещё вагон контролов, ни другие страницы не сделаны так, чтобы больше к шапке на них не возвращаться.

Пожалуйста, убери отсюда всё, что касается индекса, и доделай фото и форму.

2017-03-06 20:36 UTC, isqua commented
Надо пофиксить конфликты и добавить заголовки.

2017-03-07 17:12 UTC, alex-koshara commented
какая-то беда, не могу понять, почему на любом разрешение подгружается фон для десктопа. Изображения на месте. Стили рабочие. Не пойму.

2017-03-07 19:29 UTC, isqua commented
А что говорит инспектор?

2017-03-07 19:39 UTC, alex-koshara commented
инспектор говорит, что я налажал с ретиной :)

2017-03-07 19:52 UTC, alex-koshara commented
блин, чего-то не могу разобраться. Вроде вижу где проблема 
![image](https://cloud.githubusercontent.com/assets/16765673/23674934/adc361ae-0388-11e7-8311-15e5f1c4b83c.png)
Но почему он считает, что 5 айфон имеет минимальную ширину 1000+px...

2017-03-07 19:57 UTC, isqua commented
А ты присмотрись внимательно к этому медиа-квери!

2017-03-07 20:08 UTC, alex-koshara commented
так отож :) он должен срабатывать, когда дотяну до десктопа, а сейчас, такое ощущение, что сначала срабатывает просто `@media @retina`, а потом туда уже и последняя медиа-квери приписывается.
Точки с запятой - стоят. Скобки - закрыты...

2017-03-08 07:38 UTC, alex-koshara commented
не особо пойму, почему такой медиа запрос, ведь должно норм отрабатывать 
![image](https://cloud.githubusercontent.com/assets/16765673/23694507/4ca2fef8-03eb-11e7-87e6-ace66de855ca.png)

2017-03-08 17:56 UTC, alex-koshara commented on photo.html
> +        Фотографии<br> пользователей
Не стал слова оборачивать в `<span>`, решил просто добавить `<br>`, на десктопном разрешение он необходим, потому что ширина заголовка очень велика

2017-03-15 10:20 UTC, isqua commented
Конфликты решишь?

2017-03-15 18:21 UTC, alex-koshara commented
Шариков ждал, чтобы потом решить и слить все сразу.
Сейчас решу.

2017-03-16 20:48 UTC, isqua commented on form.html
> +                <svg class="icon icon--logo" width="75" height="23">
Можно вешать модификаторы --mobile прямо на svg, и убрать дивы?

2017-03-17 03:47 UTC, alex-koshara commented on form.html
> +                <svg class="icon icon--logo" width="75" height="23">
Сначала думал так сделать. Но потом, решил, что с оберткой в `div` будет понятней

2017-03-17 11:04 UTC, isqua commented on form.html
> +                <svg class="icon icon--logo" width="75" height="23">
Ок!

2017-03-17 14:25 UTC, isqua commented
<img width="478" alt="default" src="https://cloud.githubusercontent.com/assets/529247/24047426/b8911cb0-0b36-11e7-898f-e71183391597.png">

Кстати заметила, что даже если браузер умеет woff2, подгружается всё равно woff. Поправь пожалуйста отдельным коммитом.

2017-03-17 14:52 UTC, alex-koshara commented
Исправил

2017-03-17 22:42 UTC, isqua reviewed
Ещё не забудь удалить из коммита файлы с картинкой руки.

2017-03-17 22:42 UTC, isqua commented on less/components/header.less
> +  margin-right: auto;
Смотри ваще как у тебя свёрстано:

<img width="300" alt="default" src="https://cloud.githubusercontent.com/assets/529247/24049600/9e381704-0b3d-11e7-9edc-9a78e9bbc7bc.png">

Шапка состоит из двух частей — да. Но одна (header__bottom) безвольно повисла, и надеется только на то, что её будет отталкивать первая (header__top). Я ваще за то, чтобы блоки не только визуально были похожи на макет, но и вообще занимали интуитивну понятные места.

Смотри, визуально шапка разделена на две части. Естественной границей работает переход между затемнением и его отсутствием:

<img width="318" alt="pink-form-mobile_psd___200___h53__rgb_8____" src="https://cloud.githubusercontent.com/assets/529247/24049800/203ba1bc-0b3e-11e7-93be-e732032193c9.png">

Окей, тогда просто делим шапку на два куска и верстаем. Верхний ты сверстал хорошо, у него своя жизнь и свои паддинги. Давай внимательно посмотрим на нижний. Поставим рядом две страницы, мобильные например:

<img width="635" alt="pink-form-mobile_psd___200___h53__rgb_8____" src="https://cloud.githubusercontent.com/assets/529247/24049979/98b7fe10-0b3e-11e7-9f9d-807460dc33c9.png">

Выравнивание по верху (ты в этом прав). Обе шапки одной высоты, хоть в них разное число строк, значит нужно ограничить min-height (тут ты опять прав). И добавить паддинги (нарисованы зелёным фоном):

<img width="328" alt="a_pen_by_isqua" src="https://cloud.githubusercontent.com/assets/529247/24065137/f4728546-0b79-11e7-96bc-0c38300b275a.png">

Т.е. сам блок header тянется по размеру своих частей. И каждая часть сама рулит своей внутренней композицией: отступами и контентом.

2017-03-17 22:42 UTC, isqua commented on less/components/main-nav.less
> +  display: none;
А это зачем? Почему нельзя main-nav--group скрывать?

2017-03-17 22:42 UTC, isqua commented on less/components/main-nav.less
> +  transition: .2s all linear;
Анимируй только то (те) свойство, которое нужно. И твои приложения никогда не будут лагать (ну почти :)

2017-03-17 22:42 UTC, isqua commented on less/components/main-nav.less
> +    &:nth-child(4n) {
Это ты так последний обозначил? Так и пиши last-child :)

2017-03-17 22:42 UTC, isqua commented on less/components/main-nav.less
> +      border-bottom: 2px solid currentColor;
Кажется это написано два раза.

2017-03-17 22:42 UTC, isqua commented on less/components/main-nav.less
> +  height: 26px;
Это какие-то танцы с бубном. Зачем менять размеры и положение кнопки? Куда тыкнул туда и тыкнул. Нужно менять только положение палочек, которые образуют то бургер то крестик.

2017-03-17 22:42 UTC, isqua commented on js/main.js
> +    e.preventDefault();
Можно этого не делать, если кнопке прописать `type=button`.

2017-03-17 22:42 UTC, isqua commented on js/main.js
> +  if (mainNavNoJS) {
В файле что-то табуляция поехала.

2017-03-17 22:42 UTC, isqua commented on less/components/header.less
> +      background-size: 165%;
Ну что-то у меня фон совсем не понятный, театр этот целиком не входит. Найди как в инспекторе сделать вид что ты ретина, и посмотри и поправь.

2017-03-17 22:42 UTC, isqua commented on index.html
> +            <a href="https://htmlacademy.ru" class="main-nav__link">HTML Academy</a>
Если сначала писать классы, читать БЭМ будет удобнее.

2017-03-17 22:42 UTC, isqua commented on less/components/logo.less
> +  @media @tablet-widths {
Я бы эти модификаторы скомпоновала наоборот по медиа:
```less
// mobile
.logo__icon {
    &--mobile  { ... }
    &--tablet  { ... }
    &--desktop { ... }

    @media @tablet-widths {
        &--mobile  { ... }
        &--tablet  { ... }
        &--desktop { ... }
    }
    @media @desktop-widths {
        &--mobile  { ... }
        &--tablet  { ... }
        &--desktop { ... }
    }
}
```

Но возможно это вкусовщина :)

2017-03-17 22:42 UTC, isqua commented on less/components/main-nav.less
> +    padding: 0 40px;
Так, а почему о ширине и горизонтальных отступах думает этот блок? У тебя же есть для этого `.container`.

Кстати, не могу понять чо за блок wrapper. Он в футере был, и теперь тут есть. Собственных стилей у него никаких нет, а только селекторы типа `.main-nav .wrapper` или `.footer .wrapper`. Он кто и зачем? Не элемент ли он часом?

2017-03-17 22:43 UTC, isqua commented on less/components/header.less
> +      background-size: 165%;
<img width="975" alt="default" src="https://cloud.githubusercontent.com/assets/529247/24065465/4042ea5e-0b7c-11e7-9782-edb901bb629a.png">

2017-03-18 21:23 UTC, alex-koshara commented on less/components/logo.less
> +  left: 0;
изначально делал через `opacity`, элементы были в потоке.

2017-03-18 21:31 UTC, alex-koshara commented on less/components/logo.less
> +  @media @tablet-widths {
Переделал, но с виду мне было понятней, исходный вариант

2017-03-19 07:44 UTC, isqua commented on less/components/logo.less
> +  @media @tablet-widths {
Если тебе твой был понятнее, то стоило оставить :)

2017-03-19 18:22 UTC, alex-koshara commented on less/components/main-nav.less
> +    padding: 0 40px;
Он выполняет роль похожую на `.container`, вот только в зависимости от случая к случаю, переопределяю там свойства для сетки.
Если использовать `.container`, то придется переопределять все равно стили.
![image](https://cloud.githubusercontent.com/assets/16765673/24083550/f554a64e-0ce9-11e7-9784-369b37f15cfd.png)

Ты права, это какая-то неопределенная сущность. Откуда-то успешно я стырил эту идею. Показалось, что так очень удобно. Использую в блоке свой блок с оберткой, который от случая к случаю в каждом блоке со своими значениями

2017-03-19 18:39 UTC, alex-koshara commented on less/components/main-nav.less
> +  height: 26px;
У меня сейчас к этому привязан размер крестика. Переделать, чтобы не зависел от ширины и высоты и кнопка была больше, чем крестик? Или же убрать это и сделать крестик немного больше, по размерам гамбургера?

2017-03-19 18:55 UTC, alex-koshara commented on less/components/header.less
> +      background-size: 165%;
так по макету вроде как подбирал проценты под ретину 
![image](https://cloud.githubusercontent.com/assets/16765673/24083777/cd6e2150-0cee-11e7-8159-b919ebd9a00f.png)

2017-03-20 10:53 UTC, isqua commented on less/components/main-nav.less
> +    padding: 0 40px;
Может их делать элементами типа `footer__wrapper, `header__wrapper`?

2017-03-20 10:54 UTC, isqua commented on less/components/main-nav.less
> +  height: 26px;
> Переделать, чтобы не зависел от ширины и высоты и кнопка была больше, чем крестик

Я за такой вариант. И на макет будет похоже и код упростится.

2017-03-20 13:01 UTC, alex-koshara commented on less/components/main-nav.less
> +  height: 26px;
вот на счет последнего утверждения, я не особо уверен. Надо будет переделать кой чо, так как у меня сейчас они от ширины и высоты зависят

2017-03-20 19:32 UTC, alex-koshara commented on less/components/main-nav.less
> +  height: 26px;
оказалось в действительности проще

2017-03-20 20:09 UTC, isqua commented on less/components/header.less
> +      background-size: 165%;
А масштабировал-то ретина-картинку или не-ретина?

2017-03-20 20:11 UTC, isqua commented on form.html
> +    <div class="page-footer__wrapper  container">
Так, а куда это тут футер поплыл? Вёрстка поехала.

2017-03-20 20:17 UTC, isqua commented on less/components/header.less
> +  padding-top: 32px;
<img width="317" alt="default" src="https://cloud.githubusercontent.com/assets/529247/24119765/5a216cea-0dc3-11e7-9146-30cc59f8a88c.png">
Что-то не попал в PP.

2017-03-20 20:21 UTC, alex-koshara commented on form.html
> +    <div class="page-footer__wrapper  container">
![image](https://cloud.githubusercontent.com/assets/16765673/24119926/eaaa22ca-0dc3-11e7-84e5-485f6922f6b2.png)
похоже Гит так отображает. Уже с таким сталкивался. В коде все ок, ничего не менял

2017-03-20 20:24 UTC, alex-koshara commented on less/components/header.less
> +  padding-top: 32px;
Да-да, это выше паддинг добавил под менюху и съехало, а здесь не проверил

2017-03-20 20:26 UTC, alex-koshara commented on less/components/header.less
> +      background-size: 165%;
Ретина, все ок.
![image](https://cloud.githubusercontent.com/assets/16765673/24120159/a788ffc4-0dc4-11e7-80fc-a75a2fdbdcd6.png)

2017-03-20 20:37 UTC, isqua commented on less/components/main-nav.less
> +    margin-right: 80px;
Сделал бы лучше у `main-nav__group--links` `justify-content: space-between`, раз он у тебя флексовый.

2017-03-20 20:37 UTC, isqua commented on less/components/header.less
> +      background-size: 165%;
Да, у меня теперь тоже ок.

2017-03-20 20:37 UTC, isqua commented on less/components/main-nav.less
> +  display: block;
Лучше выезжающее меню позиционировать абсолютно, чтобы оно не сдвигало контент. Когда оно в потоке, браузеру нужно пересчитать и перерисовать всю страницу после меню. В хроме в инспекторе можно включить показ зон, которые перерисовываются:

<img width="375" alt="fullscreen_20_03_17_23_34" src="https://cloud.githubusercontent.com/assets/529247/24120495/dab3261c-0dc5-11e7-874a-ec6777a05362.png">

<img width="547" alt="banners_and_alerts_and_" src="https://cloud.githubusercontent.com/assets/529247/24120522/f8d8ddda-0dc5-11e7-9e5d-50b788479bfa.png">

И тогда ты увидишь, что при открытии меню всё что ниже перерендеривается:
https://www.dropbox.com/s/i9xyd4vop4ez8qk/pink-menu-repaint_brwlu.mp4?dl=0

На мобильных устройствах это сажает батарейку, за что ты так с пользователями :)

2017-03-20 20:37 UTC, isqua commented on less/components/main-nav.less
> +  right: 0;
Почему кнопка меняет своё положение при открытии?

2017-03-20 20:58 UTC, isqua commented on form.html
> +    <div class="page-footer__wrapper  container">
Смотри, в мастере всё нормально с футером:
<img width="845" alt="pink" src="https://cloud.githubusercontent.com/assets/529247/24121324/f2ed6e38-0dc8-11e7-9f66-83fea3fa7d37.png">

А в этой ветке на странице формы и фотографий поехало:
<img width="845" alt="default" src="https://cloud.githubusercontent.com/assets/529247/24121376/195979d6-0dc9-11e7-99b5-d37e14599c4b.png">
Наверное конфликты не правильно разрулил при ребейзе.

2017-03-22 10:47 UTC, isqua approved these changes
Остальное хорошо! А можешь починки футера в отдельный коммит вынетси, а остальные, про шапку — посквошить?

2017-03-22 10:47 UTC, isqua commented on less/components/main-nav.less
> +  right: 20px;
Какая разница между top:20, right:20 и top:18,right:20? Давай у открытого гамбургера будут такие же координаты, как у закрытого.

2017-03-22 10:47 UTC, isqua commented on less/components/main-nav.less
> +    right: 40px;
И тут. Было 42/40, стало 41/40. Давай не менять координаты.

2017-03-22 19:01 UTC, alex-koshara commented on form.html
> +        <a class="social__link" href="http://facebook.com">
Да что же это такое... :)
1) из текущего состояния, удалил все что связано с футером
2) добавил фиксап к комиту про хедер
3) вернул все на место
4) добавил фиксап к комиту про починку футера
5) сделал ребейз и оно снова в хедере отображается

2017-03-22 19:01 UTC, alex-koshara commented on form.html
> +        <a class="social__link" href="http://facebook.com">
перепроверил в логах хеш комитов, не ошибся, да и при интерактивном ребейзе все ок было, по одному фиксапу к каждому комиту

2017-03-22 19:30 UTC, alex-koshara commented
можно сливать с мастером?

2017-03-22 20:08 UTC, isqua commented
Нет, завтра вместе поправим.

2017-03-23 19:31 UTC, merged