Сверстать футер; FIX #3
alex-koshara/pink pull request #9
Opened 2017-01-15 19:46 UTC by alex-koshara

#3

2017-01-16 11:40 UTC, isqua commented
Посмотри внимательно [дифф](https://github.com/alex-koshara/pink/pull/9/files) и скажи сам, что в нём не так?

2017-01-16 18:33 UTC, alex-koshara commented
старые косяки перетащил из другой ветки, не пожаты СВГ. И то что в Диффе находится то, что там не должно находиться и переехало из другой ветки. Последнее, видимо, самое главное

2017-01-16 20:18 UTC, isqua requested changes
В целом клёво! Давай ещё его [прижмём к низу](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/).

2017-01-16 20:18 UTC, isqua commented on less/components/social.less
> +    margin-left: 7px;
Шёл тяжёлый 2017-й, мы попадали в макеты как могли...

Судя по направляющим, дизайнер хотел, чтобы кнопки всегда были по центру
<img width="513" alt="" src="https://cloud.githubusercontent.com/assets/529247/21997609/4be61d1e-dc41-11e6-8b97-1441fc1a5eb0.png">

Но у тебя они поедут в сторону, если компания будет называться чуть длиннее:
<img width="969" alt="pink" src="https://cloud.githubusercontent.com/assets/529247/21997663/858df050-dc41-11e6-800f-279afb43c6d6.png">

Придумай, как по центру сделать.

2017-01-16 20:18 UTC, isqua commented on img/icons/youtube.svg
> +<svg version="1" xmlns="http://www.w3.org/2000/svg" width="15" height="14" viewBox="0 0 14.64 13.96"><path fill="currentColor" d="M1.775 13.78C.799 14.257 0 13.758 0 12.671V1.29C0 .202.799-.295 1.775
Плей какой-то ущербный:
<img width="62" alt="pink" src="https://cloud.githubusercontent.com/assets/529247/21997700/bbc7152a-dc41-11e6-8848-e11cbcb4846a.png">
Похоже надо подвинуть вправо:
<img width="62" alt="pink" src="https://cloud.githubusercontent.com/assets/529247/21997734/e0a346de-dc41-11e6-98fd-3ec8a6a767f1.png">
Поправь SVG, чтобы лучше встала.

2017-01-16 20:23 UTC, alex-koshara commented on form.html
> +          <source media="(min-width: 1025px)" srcset="img/logo/logo-pink-blue-desktop.svg">
эта ещё одна из мелочей, которая перекочевала частично из другого ПР и нужна, чтобы на iPad Pro был планшет, а не Десктоп

2017-01-16 20:27 UTC, alex-koshara commented on img/icons/youtube.svg
> +<svg version="1" xmlns="http://www.w3.org/2000/svg" width="15" height="14" viewBox="0 0 14.64 13.96"><path fill="currentColor" d="M1.775 13.78C.799 14.257 0 13.758 0 12.671V1.29C0 .202.799-.295 1.775
вроде норм?
![image](https://cloud.githubusercontent.com/assets/16765673/21997967/3dfb927c-dc43-11e6-911a-52a2995e2a5b.png)
Не пойму, что с ним не так и чего ему подравить

2017-01-16 20:29 UTC, isqua commented on form.html
> +          <source media="(min-width: 1025px)" srcset="img/logo/logo-pink-blue-desktop.svg">
А что будет, если iPad Pro развернуть горизонтально? А сколько диагональ у iPad pro?

2017-01-16 20:29 UTC, isqua commented on img/icons/youtube.svg
> +<svg version="1" xmlns="http://www.w3.org/2000/svg" width="15" height="14" viewBox="0 0 14.64 13.96"><path fill="currentColor" d="M1.775 13.78C.799 14.257 0 13.758 0 12.671V1.29C0 .202.799-.295 1.775
Подвинуть плей буквально на пару пикселей вправо.

2017-01-16 20:33 UTC, alex-koshara commented on form.html
> +          <source media="(min-width: 1025px)" srcset="img/logo/logo-pink-blue-desktop.svg">
будет вид десктопа, с обычный ноут разрешение 1366px горизонталь получится

2017-01-16 20:35 UTC, isqua commented on form.html
> +          <source media="(min-width: 1025px)" srcset="img/logo/logo-pink-blue-desktop.svg">
А почему в портретном режиме десктопный вид тебя не устраивает?

2017-01-16 20:43 UTC, alex-koshara commented on form.html
> +          <source media="(min-width: 1025px)" srcset="img/logo/logo-pink-blue-desktop.svg">
там будет все крупней, удобней будет тыкать (я так думаю). 
![image](https://cloud.githubusercontent.com/assets/16765673/21998372/673c56c4-dc45-11e6-8ea3-97928d16b698.png)
я вот допустим так ничего не вижу, придется пальцы в разные стороны разводить, чтобы увидеть текст, а при горизонтальном положение, уже хоть что-то видно и даже текст читаемый

2017-01-16 21:08 UTC, isqua commented on form.html
> +          <source media="(min-width: 1025px)" srcset="img/logo/logo-pink-blue-desktop.svg">
Ну во-первых, у тебя масштаб 50%, т.к. в твой экран целый айпад не влезает. Это показывает чиселка после ширины и высоты в адаптивной панели. Во-вторых, ты сидишь за компом, а айпад держат в руках — расстояние меньше. Во-вторых, ты видел людей с айпадами про? В-третьих, а человеки с десктопами такой ширины что увидят?

2017-01-17 11:32 UTC, alex-koshara commented on less/components/social.less
> +    margin-left: 7px;
есть вариант не на флоутах сделать это? Только так пока придумал.

2017-01-17 12:19 UTC, alex-koshara commented on less/components/social.less
> +    margin-left: 7px;
Либо ограничить ширину, как вариант №2

2017-01-17 12:27 UTC, alex-koshara commented on form.html
> +          <source media="(min-width: 1025px)" srcset="img/logo/logo-pink-blue-desktop.svg">
убедительно

2017-01-17 12:40 UTC, isqua commented on less/components/social.less
> +    margin-left: 7px;
А как на флоутах? Ограничить ширину чего именно?

2017-01-17 12:44 UTC, alex-koshara commented on less/components/social.less
> +    margin-left: 7px;
делаю 3 элемента футера, миксование получается (лого, социалки, копирайт), им ширину по 33%, и уже в блоках выравнивание, ща запулю

2017-01-17 13:13 UTC, isqua commented on less/components/social.less
> +    margin-left: 7px;
Звучит ок!

2017-01-17 19:08 UTC, isqua commented on less/components/social.less
> +    padding-top: 3px 15px 0;
?

2017-01-17 19:08 UTC, isqua commented on less/components/social.less
> +    margin-left: 7px;
Вот это можно убрать?

2017-01-17 19:08 UTC, isqua commented on less/components/social.less
> +    margin-right: 0;
А это?

2017-01-17 19:08 UTC, isqua commented on less/components/social.less
> +    margin-right: 0;
А можно сделать так, чтобы последний не было особенным, а расстояния между ссылками остались 12px :) Но не обязательно.

2017-01-17 19:10 UTC, isqua commented
Выглядит ок! Прижмёшь к низу?

2017-01-17 19:22 UTC, alex-koshara commented on less/components/social.less
> +    padding-top: 3px 15px 0;
здесь решил по бокам отступы сделать, чтобы при переполнение не прилипали. Или не стоило? а 3 - это для PP

2017-01-17 19:29 UTC, alex-koshara commented
точняк, прижать забыл

2017-01-18 09:53 UTC, isqua commented
Прижал — хорошо. Но стрёмно, что контент футера прям касается нижней границы. Добавь небольшой паддинг. И чего у тебя обводка социокнопок стала тёмно-синей?

2017-03-06 20:35 UTC, isqua commented
Ну чочо?

2017-03-07 06:14 UTC, alex-koshara commented
Ой, ты здесь :) а я там борю штуку с фильтрами, которую можно мышкой таскать

2017-03-07 16:12 UTC, alex-koshara commented
👀

2017-03-15 10:47 UTC, isqua reviewed
Классно! Давай закончим.

2017-03-15 10:47 UTC, isqua commented on form.html
> +      <a href="http://htmlacademy.ru" class="copyright">
Сейчас ссылка ховерится даже когда наводишь сильно левее. Давай ссылку завернём в секшн, и секшну будем всякое про флекс рассказывать, а сама ссылка пусть будет по размеру своего контента.

<img width="342" alt="pink" src="https://cloud.githubusercontent.com/assets/529247/23944868/764adfec-0985-11e7-95d1-290a947343db.png">

Вот тут желтый фон — секшн, а обведённое — ссылка.

2017-03-15 10:47 UTC, isqua commented on less/components/footer.less
> +  padding-bottom: 10px;
Давай может 30? Щас всё тесно.

2017-03-15 10:47 UTC, isqua commented on less/components/footer.less
> +    justify-content: center;
space-between? Тогда не придётся колдовать с margin: auto наверное.

2017-03-15 10:47 UTC, isqua commented on less/components/social.less
> +    margin-right: 0;
Можно сделать просто каждой ссылке: `margin: 0 6px`, тогда никого не надо будет выделять.

2017-03-15 19:50 UTC, isqua commented on form.html
> +      <a href="http://htmlacademy.ru" class="copyright">
Кто поменял разметку только на одной странице, не знаешь?

2017-03-15 19:51 UTC, alex-koshara commented on form.html
> +      <a href="http://htmlacademy.ru" class="copyright">
чорд) кажись знаю

2017-03-15 19:56 UTC, isqua commented on form.html
> +      <a href="index.html" class="logo logo--footer">
Если это ссылка, то везде надо делать ссылкой, и делать эффект при наведении.

2017-03-15 19:59 UTC, alex-koshara commented on form.html
> +      <a href="index.html" class="logo logo--footer">
т.е. в `index` остаить просто div нельзя?

2017-03-15 20:23 UTC, isqua commented on form.html
> +      <a href="index.html" class="logo logo--footer">
Так у тебя только на одной странице была ссылка.

2017-03-15 20:30 UTC, isqua commented on less/components/copyright.less
> +  color: @secondaryColor;
Давай ещё добавим `transition: color .15s` для красоты.

2017-03-15 20:30 UTC, isqua commented on less/components/social.less
> +  border-radius: 50%;
И тут добавим `transition: border-color .15s`

2017-03-15 20:30 UTC, isqua approved these changes
И МОЖНАААА СКВОШИТЬСЯ! 🎱

2017-03-15 20:31 UTC, alex-koshara commented on form.html
> +      <a href="index.html" class="logo logo--footer">
вернул на обычную картинку. Там есть некоторая заморочка с путями и отсутствие стайлгайда

2017-03-15 20:47 UTC, isqua commented
Ну всё, жми зелёную кнопку Merge!

2017-03-15 20:54 UTC, merged